Traceback (most recent call last):
  File "Make_Y_data_3.py", line 19, in <module>
    t = xr.open_mfdataset('/rc_scratch/reba1583/Y_variables_98th/T2M'+str(year)+'*')
  File "/home/reba1583/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 873, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Traceback (most recent call last):
  File "Make_Y_data_3.py", line 19, in <module>
    t = xr.open_mfdataset('/rc_scratch/reba1583/Y_variables_98th/T2M'+str(year)+'*')
  File "/home/reba1583/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 873, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Traceback (most recent call last):
  File "Make_Y_data_3.py", line 19, in <module>
    t = xr.open_mfdataset('/rc_scratch/reba1583/Y_variables_98th/T2M'+str(year)+'*')
  File "/home/reba1583/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 873, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Traceback (most recent call last):
  File "Make_Y_data_3.py", line 19, in <module>
    t = xr.open_mfdataset('/rc_scratch/reba1583/Y_variables_98th/T2M'+str(year)+'*')
  File "/home/reba1583/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 873, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Traceback (most recent call last):
  File "Make_Y_data_3.py", line 19, in <module>
    t = xr.open_mfdataset('/rc_scratch/reba1583/Y_variables_98th/T2M'+str(year)+'*')
  File "/home/reba1583/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 873, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Traceback (most recent call last):
  File "Make_Y_data_3.py", line 19, in <module>
    t = xr.open_mfdataset('/rc_scratch/reba1583/Y_variables_98th/T2M'+str(year)+'*')
  File "/home/reba1583/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 873, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Traceback (most recent call last):
  File "Make_Y_data_3.py", line 19, in <module>
    t = xr.open_mfdataset('/rc_scratch/reba1583/Y_variables_98th/T2M'+str(year)+'*')
  File "/home/reba1583/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 873, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Traceback (most recent call last):
  File "Make_Y_data_3.py", line 19, in <module>
    t = xr.open_mfdataset('/rc_scratch/reba1583/Y_variables_98th/T2M'+str(year)+'*')
  File "/home/reba1583/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 873, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Traceback (most recent call last):
  File "Make_Y_data_3.py", line 19, in <module>
    t = xr.open_mfdataset('/rc_scratch/reba1583/Y_variables_98th/T2M'+str(year)+'*')
  File "/home/reba1583/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 873, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Traceback (most recent call last):
  File "Make_Y_data_3.py", line 19, in <module>
    t = xr.open_mfdataset('/rc_scratch/reba1583/Y_variables_98th/T2M'+str(year)+'*')
  File "/home/reba1583/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 873, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Traceback (most recent call last):
  File "Make_Y_data_3.py", line 19, in <module>
    t = xr.open_mfdataset('/rc_scratch/reba1583/Y_variables_98th/T2M'+str(year)+'*')
  File "/home/reba1583/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 873, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Traceback (most recent call last):
  File "Make_Y_data_3.py", line 19, in <module>
    t = xr.open_mfdataset('/rc_scratch/reba1583/Y_variables_98th/T2M'+str(year)+'*')
  File "/home/reba1583/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 873, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Traceback (most recent call last):
  File "Make_Y_data_3.py", line 19, in <module>
    t = xr.open_mfdataset('/rc_scratch/reba1583/Y_variables_98th/T2M'+str(year)+'*')
  File "/home/reba1583/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 873, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Traceback (most recent call last):
  File "Make_Y_data_3.py", line 19, in <module>
    t = xr.open_mfdataset('/rc_scratch/reba1583/Y_variables_98th/T2M'+str(year)+'*')
  File "/home/reba1583/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 873, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Traceback (most recent call last):
  File "Make_Y_data_3.py", line 19, in <module>
    t = xr.open_mfdataset('/rc_scratch/reba1583/Y_variables_98th/T2M'+str(year)+'*')
  File "/home/reba1583/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 873, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Traceback (most recent call last):
  File "Make_Y_data_3.py", line 19, in <module>
    t = xr.open_mfdataset('/rc_scratch/reba1583/Y_variables_98th/T2M'+str(year)+'*')
  File "/home/reba1583/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 873, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Traceback (most recent call last):
  File "Make_Y_data_3.py", line 19, in <module>
    t = xr.open_mfdataset('/rc_scratch/reba1583/Y_variables_98th/T2M'+str(year)+'*')
  File "/home/reba1583/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 873, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Traceback (most recent call last):
  File "Make_Y_data_3.py", line 19, in <module>
    t = xr.open_mfdataset('/rc_scratch/reba1583/Y_variables_98th/T2M'+str(year)+'*')
  File "/home/reba1583/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 873, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Traceback (most recent call last):
  File "Make_Y_data_3.py", line 19, in <module>
    t = xr.open_mfdataset('/rc_scratch/reba1583/Y_variables_98th/T2M'+str(year)+'*')
  File "/home/reba1583/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 873, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Traceback (most recent call last):
  File "Make_Y_data_3.py", line 19, in <module>
    t = xr.open_mfdataset('/rc_scratch/reba1583/Y_variables_98th/T2M'+str(year)+'*')
  File "/home/reba1583/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 873, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Traceback (most recent call last):
  File "Make_Y_data_3.py", line 19, in <module>
    t = xr.open_mfdataset('/rc_scratch/reba1583/Y_variables_98th/T2M'+str(year)+'*')
  File "/home/reba1583/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 873, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Traceback (most recent call last):
  File "Make_Y_data_3.py", line 19, in <module>
    t = xr.open_mfdataset('/rc_scratch/reba1583/Y_variables_98th/T2M'+str(year)+'*')
  File "/home/reba1583/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 873, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Traceback (most recent call last):
  File "Make_Y_data_3.py", line 19, in <module>
    t = xr.open_mfdataset('/rc_scratch/reba1583/Y_variables_98th/T2M'+str(year)+'*')
  File "/home/reba1583/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 873, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Traceback (most recent call last):
  File "Make_Y_data_3.py", line 19, in <module>
    t = xr.open_mfdataset('/rc_scratch/reba1583/Y_variables_98th/T2M'+str(year)+'*')
  File "/home/reba1583/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 873, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Traceback (most recent call last):
  File "Make_Y_data_3.py", line 19, in <module>
    t = xr.open_mfdataset('/rc_scratch/reba1583/Y_variables_98th/T2M'+str(year)+'*')
  File "/home/reba1583/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 873, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Traceback (most recent call last):
  File "Make_Y_data_3.py", line 19, in <module>
    t = xr.open_mfdataset('/rc_scratch/reba1583/Y_variables_98th/T2M'+str(year)+'*')
  File "/home/reba1583/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 873, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Traceback (most recent call last):
  File "Make_Y_data_3.py", line 19, in <module>
    t = xr.open_mfdataset('/rc_scratch/reba1583/Y_variables_98th/T2M'+str(year)+'*')
  File "/home/reba1583/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 873, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Traceback (most recent call last):
  File "Make_Y_data_3.py", line 19, in <module>
    t = xr.open_mfdataset('/rc_scratch/reba1583/Y_variables_98th/T2M'+str(year)+'*')
  File "/home/reba1583/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 873, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Traceback (most recent call last):
  File "Make_Y_data_3.py", line 19, in <module>
    t = xr.open_mfdataset('/rc_scratch/reba1583/Y_variables_98th/T2M'+str(year)+'*')
  File "/home/reba1583/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 873, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Traceback (most recent call last):
  File "Make_Y_data_3.py", line 19, in <module>
    t = xr.open_mfdataset('/rc_scratch/reba1583/Y_variables_98th/T2M'+str(year)+'*')
  File "/home/reba1583/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 873, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Traceback (most recent call last):
  File "Make_Y_data_3.py", line 19, in <module>
    t = xr.open_mfdataset('/rc_scratch/reba1583/Y_variables_98th/T2M'+str(year)+'*')
  File "/home/reba1583/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 873, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Traceback (most recent call last):
  File "Make_Y_data_3.py", line 19, in <module>
    t = xr.open_mfdataset('/rc_scratch/reba1583/Y_variables_98th/T2M'+str(year)+'*')
  File "/home/reba1583/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 873, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Traceback (most recent call last):
  File "Make_Y_data_3.py", line 19, in <module>
    t = xr.open_mfdataset('/rc_scratch/reba1583/Y_variables_98th/T2M'+str(year)+'*')
  File "/home/reba1583/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 873, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Traceback (most recent call last):
  File "Make_Y_data_3.py", line 19, in <module>
    t = xr.open_mfdataset('/rc_scratch/reba1583/Y_variables_98th/T2M'+str(year)+'*')
  File "/home/reba1583/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 873, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Traceback (most recent call last):
  File "Make_Y_data_3.py", line 19, in <module>
    t = xr.open_mfdataset('/rc_scratch/reba1583/Y_variables_98th/T2M'+str(year)+'*')
  File "/home/reba1583/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 873, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Traceback (most recent call last):
  File "Make_Y_data_3.py", line 19, in <module>
    t = xr.open_mfdataset('/rc_scratch/reba1583/Y_variables_98th/T2M'+str(year)+'*')
  File "/home/reba1583/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 873, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Traceback (most recent call last):
  File "Make_Y_data_3.py", line 19, in <module>
    t = xr.open_mfdataset('/rc_scratch/reba1583/Y_variables_98th/T2M'+str(year)+'*')
  File "/home/reba1583/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 873, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Traceback (most recent call last):
  File "Make_Y_data_3.py", line 19, in <module>
    t = xr.open_mfdataset('/rc_scratch/reba1583/Y_variables_98th/T2M'+str(year)+'*')
  File "/home/reba1583/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 873, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Traceback (most recent call last):
  File "Make_Y_data_3.py", line 19, in <module>
    t = xr.open_mfdataset('/rc_scratch/reba1583/Y_variables_98th/T2M'+str(year)+'*')
  File "/home/reba1583/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 873, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
Traceback (most recent call last):
  File "Make_Y_data_3.py", line 19, in <module>
    t = xr.open_mfdataset('/rc_scratch/reba1583/Y_variables_98th/T2M'+str(year)+'*')
  File "/home/reba1583/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 873, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
